apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: productappidentity
spec:
  type: 0
  ResourceID: "/subscriptions/86d61f02/resourcegroups/MyResources/providers/Microsoft.ManagedIdentity/userAssignedIdentities/productappidentity"
  ClientID: "d11bfd21"
