# Default values for state-secret-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Object for application data
appData:

  # Namespace we are deployment our application into
  namespace: default

  # This is the key-vault URL
  keyVaultUrl: "https://readybank.vault.azure.net/"

  # This is the client id for the User-Managed Service Identity
  msiClientId: "d11bfd21-7726-4a73-ab0d-8b640b50ae48"

  # Application Environment
  applicationEnvironment: "Production"

  # Application Version
  applicationVersion: "1.5"

  # Application Revision Number
  applicationRevision: "3.0"

# Number of pods we need for our application
replicaCount: 1

# Image location and pull policy
image:
  imageName: izzymsft/contosodemo
  imageVersion: 1.9

service:

  # The type of service
  type: LoadBalancer

  # The ports to bind on the services
  port: 8080

  # Toggle this to enable/disable the public loadbalancer service
  exposePublicEndpoint: true