---
{{- if eq .Values.appData.namespace "default" }}

{{ else }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appData.namespace }}
  labels:
    app.kubernetes.io/name: contoso-demo
    app.kubernetes.io/part-of: contoso-demo
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-api-configs
  namespace: {{ .Values.appData.namespace }}
  labels:
    app.kubernetes.io/name: contoso-demo
    app.kubernetes.io/part-of: contoso-demo
data:
  key.vault.url: {{ .Values.appData.keyVaultUrl }}
  msi.client.id: {{ .Values.appData.msiClientId }}
  application.environment: {{ .Values.appData.applicationEnvironment }}