---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    active: contosopodid
    app: contosodeployment
    aadpodidbinding: keyvaultsampleidentity
  name: contosodeployment
  namespace: {{ .Values.appData.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ready-api
      aadpodidbinding: keyvaultsampleidentity
  template:
    metadata:
      labels:
        k8s-app: ready-api
        aadpodidbinding: keyvaultsampleidentity
    spec:
      containers:
        - image: {{ .Values.image.imageName }}:{{ .Values.image.imageVersion }}
          name: contosodemo
          ports:
            - containerPort: {{ .Values.service.port }}
              name: frontdoor
          env:
            - name: KEY_VAULT_URL
              valueFrom:
                configMapKeyRef:
                  name: contoso-api-configs
                  key: key.vault.url
            - name: MSI_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: contoso-api-configs
                  key: msi.client.id