---
# External Load Balancer
{{- if eq .Values.service.exposePublicEndpoint true }}
apiVersion: v1
kind: Service
metadata:
  name: contoso-api-service-external
  namespace: {{ .Values.appData.namespace }}
  labels:
    k8s-app: contosopodid-external-loadbalancer
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "contoso-api-service"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name : frontdoor
      port:  {{ .Values.service.port }}
      protocol: TCP
      targetPort: frontdoor
  selector:
    k8s-app: ready-api
{{- end }}
---
# Internal Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: contoso-api-service-internal
  namespace: {{ .Values.appData.namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    k8s-app: contosopodid-internal-loadbalancer
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "contoso-api-service"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name : frontdoor
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: frontdoor
  selector:
    k8s-app: ready-api